# 1. Normalization (Scaling Data to a Range)

In [20]:
import pandas as pd
import numpy as np

# Creating a sample dataset
data = {'Feature': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)
df

   Feature
0       10
1       20
2       30
3       40
4       50

1) min-max scaling

In [8]:
df['feature_normalized']=(df['Feature']-df['Feature'].min())/(df['Feature'].max()-df['Feature'].min())
df

   Feature  feature_normalized
0       10                0.00
1       20                0.25
2       30                0.50
3       40                0.75
4       50                1.00

# 2. Standardization

In [10]:
df['Feature_standarized']=(df['Feature']-df['Feature'].mean())/df['Feature'].std()
df

   Feature  feature_normalized  Feature_standarized
0       10                0.00            -1.264911
1       20                0.25            -0.632456
2       30                0.50             0.000000
3       40                0.75             0.632456
4       50                1.00             1.264911

# 3. Log Transformation (Handling Skewed Data)

In [12]:
df['Feature_log']=np.log(df['Feature'])
df

   Feature  feature_normalized  Feature_standarized  Feature_log
0       10                0.00            -1.264911     2.302585
1       20                0.25            -0.632456     2.995732
2       30                0.50             0.000000     3.401197
3       40                0.75             0.632456     3.688879
4       50                1.00             1.264911     3.912023

# 4. power transformation

In [23]:
from sklearn.preprocessing import PowerTransformer
pt = PowerTransformer(method='yeo-johnson')
df['Feature_Power'] = pt.fit_transform(df[['Feature']])

AttributeError: module 'numpy' has no attribute 'warnings'

# 5. Binning (Converting Continuous Data to Categorical)

In [38]:
df['Feature_Binned'] = pd.cut(df['Feature'], bins=3, labels=['Low', 'Medium', 'High'])
df

   Feature Feature_Binned
0       10            Low
1       20            Low
2       30         Medium
3       40           High
4       50           High