In [1]:
import pandas as pd

In [2]:
dff=pd.read_csv("heart.csv")

In [3]:
dff

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [4]:
dff.shape

(303, 14)

In [5]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trtbps    303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalachh  303 non-null    int64
 8   exng      303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64
 11  caa       303 non-null    int64
 12  thall     303 non-null    int64
 13  output    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [6]:

# are all columns are visible in dataframe

In [7]:
pd.set_option('display.max_columns',14)

In [8]:
dff

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [9]:
pd.set_option('display.max_rows',16)

In [10]:
dff

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [11]:
df=pd.read_csv('o2Saturation.csv')

In [12]:
df

      98.6
0     98.6
1     98.6
2     98.6
3     98.1
4     97.5
...    ...
3580  98.6
3581  98.6
3582  98.6
3583  98.6
3584  98.6

[3585 rows x 1 columns]

In [13]:
pd.set_option('display.max_rows',64)

In [14]:
# first five columns
df.head()

   98.6
0  98.6
1  98.6
2  98.6
3  98.1
4  97.5

In [15]:
#first 10 rows
df.head(10)

   98.6
0  98.6
1  98.6
2  98.6
3  98.1
4  97.5
5  97.5
6  97.5
7  97.5
8  97.5
9  97.5

In [16]:
# last five columns
df.tail()

      98.6
3580  98.6
3581  98.6
3582  98.6
3583  98.6
3584  98.6

In [17]:
df.tail(20)

      98.6
3565  98.6
3566  98.6
3567  98.6
3568  99.3
3569  99.6
3570  98.8
3571  99.3
3572  98.8
3573  99.3
3574  99.6
3575  99.6
3576  98.8
3577  98.6
3578  98.6
3579  98.6
3580  98.6
3581  98.6
3582  98.6
3583  98.6
3584  98.6

In [18]:
people={"name":"Rohan","last":"pol","email":"polrohan10@gmail.com"}
people

{'name': 'Rohan', 'last': 'pol', 'email': 'polrohan10@gmail.com'}

In [19]:
people={"name":["rohan","bablu","husen","mahesh"],
        "last":["pol","pol","shaikh","jadhav"],
        "email":["polrohan10@gmail.com","poldhananjay20@gmil.com","husen@gmial.com","mahesh@gmail.com"]
       }
people

{'name': ['rohan', 'bablu', 'husen', 'mahesh'],
 'last': ['pol', 'pol', 'shaikh', 'jadhav'],
 'email': ['polrohan10@gmail.com',
  'poldhananjay20@gmil.com',
  'husen@gmial.com',
  'mahesh@gmail.com']}

In [20]:
# dictionary converted into dataframe
df=pd.DataFrame(people)
df

     name    last                    email
0   rohan     pol     polrohan10@gmail.com
1   bablu     pol  poldhananjay20@gmil.com
2   husen  shaikh          husen@gmial.com
3  mahesh  jadhav         mahesh@gmail.com

In [21]:
df.head()

     name    last                    email
0   rohan     pol     polrohan10@gmail.com
1   bablu     pol  poldhananjay20@gmil.com
2   husen  shaikh          husen@gmial.com
3  mahesh  jadhav         mahesh@gmail.com

In [22]:
# series -row of single column
# dataframe- container for multiple series
df["email"]

0       polrohan10@gmail.com
1    poldhananjay20@gmil.com
2            husen@gmial.com
3           mahesh@gmail.com
Name: email, dtype: object

In [23]:
type(df["email"])

pandas.core.series.Series

In [24]:
# acess multiple values
df[["name","last"]]

     name    last
0   rohan     pol
1   bablu     pol
2   husen  shaikh
3  mahesh  jadhav

In [25]:
type(df[["name","last"]])

pandas.core.frame.DataFrame

In [26]:
#acess all columns of dataframe
df.columns

Index(['name', 'last', 'email'], dtype='object')

In [27]:
# loc label based
# iloc integer position based
df.iloc[0]

name                    rohan
last                      pol
email    polrohan10@gmail.com
Name: 0, dtype: object

In [28]:
# acess two rows
df.iloc[[0,1]]

    name last                    email
0  rohan  pol     polrohan10@gmail.com
1  bablu  pol  poldhananjay20@gmil.com

In [29]:
df.head(2)

    name last                    email
0  rohan  pol     polrohan10@gmail.com
1  bablu  pol  poldhananjay20@gmil.com

# Rows of specific column only

In [30]:
df.iloc[[0,1],2]

0       polrohan10@gmail.com
1    poldhananjay20@gmil.com
Name: email, dtype: object

In [31]:
df.iloc[[1,2],[0,1]]

    name    last
1  bablu     pol
2  husen  shaikh

acess using loc

In [32]:
df.loc[0]

name                    rohan
last                      pol
email    polrohan10@gmail.com
Name: 0, dtype: object

In [33]:
df.loc[[1,2]]

    name    last                    email
1  bablu     pol  poldhananjay20@gmil.com
2  husen  shaikh          husen@gmial.com

In [34]:
df.loc[[1,2],'name']

1    bablu
2    husen
Name: name, dtype: object

In [35]:
df.loc[[0,1],["name","last"]]

    name last
0  rohan  pol
1  bablu  pol

csv file-comma seperated values

In [36]:
dff

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [37]:
dff.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

Acess the output column

In [38]:
dff["output"]

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64

How many values in output column 0 or 1

In [39]:
dff["output"].value_counts()

1    165
0    138
Name: output, dtype: int64

# Acessing specific row of dataframe

In [40]:
dff.iloc[0]

age          63.0
sex           1.0
cp            3.0
trtbps      145.0
chol        233.0
fbs           1.0
restecg       0.0
thalachh    150.0
exng          0.0
oldpeak       2.3
slp           0.0
caa           0.0
thall         1.0
output        1.0
Name: 0, dtype: float64

In [41]:
# acessing top 3 rows and slp column
dff.loc[[1,2,3],"slp"]

1    0
2    2
3    2
Name: slp, dtype: int64

In [42]:
df

     name    last                    email
0   rohan     pol     polrohan10@gmail.com
1   bablu     pol  poldhananjay20@gmil.com
2   husen  shaikh          husen@gmial.com
3  mahesh  jadhav         mahesh@gmail.com

# index : integer identifiers for row

In [43]:
df.set_index("email")

                           name    last
email
polrohan10@gmail.com      rohan     pol
poldhananjay20@gmil.com   bablu     pol
husen@gmial.com           husen  shaikh
mahesh@gmail.com         mahesh  jadhav

In [44]:
# our data frame does not allow us to change
#because pandas does not allow such operations 
df

     name    last                    email
0   rohan     pol     polrohan10@gmail.com
1   bablu     pol  poldhananjay20@gmil.com
2   husen  shaikh          husen@gmial.com
3  mahesh  jadhav         mahesh@gmail.com

In [45]:
data=df.set_index("email")

In [46]:
data

                           name    last
email
polrohan10@gmail.com      rohan     pol
poldhananjay20@gmil.com   bablu     pol
husen@gmial.com           husen  shaikh
mahesh@gmail.com         mahesh  jadhav

In [47]:
df.set_index("email",inplace=True)

In [48]:
df

                           name    last
email
polrohan10@gmail.com      rohan     pol
poldhananjay20@gmil.com   bablu     pol
husen@gmial.com           husen  shaikh
mahesh@gmail.com         mahesh  jadhav

In [49]:
df.reset_index(inplace=True)

In [50]:
df

                     email    name    last
0     polrohan10@gmail.com   rohan     pol
1  poldhananjay20@gmil.com   bablu     pol
2          husen@gmial.com   husen  shaikh
3         mahesh@gmail.com  mahesh  jadhav

In [51]:
pd.set_option('display.max_rows',61)

In [52]:
df

                     email    name    last
0     polrohan10@gmail.com   rohan     pol
1  poldhananjay20@gmil.com   bablu     pol
2          husen@gmial.com   husen  shaikh
3         mahesh@gmail.com  mahesh  jadhav

In [53]:
dff

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [54]:
pd.set_option('display.max_rows',78)

In [55]:
dff

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [56]:
dff.set_index('age',inplace=True)

In [57]:
dff

,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
age,,,,,,,,,,,,,
63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [58]:
dff.reset_index(inplace=True)

In [59]:
dff

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [60]:
dfff=pd.read_csv("heart.csv",index_col="age")

In [61]:
dfff

,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
age,,,,,,,,,,,,,
63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [62]:
dfff.sort_index(True)

C:\Users\polro\AppData\Local\Temp\ipykernel_15604\3250351696.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.sort_index will be keyword-only.
  dfff.sort_index(True)

,caa,chol,cp,exng,fbs,oldpeak,output,restecg,sex,slp,thalachh,thall,trtbps
age,,,,,,,,,,,,,
63,0,233,3,0,1,2.3,1,0,1,0,150,1,145
37,0,250,2,0,0,3.5,1,1,1,0,187,2,130
41,0,204,1,0,0,1.4,1,0,0,2,172,2,130
56,0,236,1,0,0,0.8,1,1,1,2,178,2,120
57,0,354,0,1,0,0.6,1,1,0,2,163,2,120
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,0,241,0,1,0,0.2,0,1,0,1,123,3,140
45,0,264,3,0,0,1.2,0,1,1,1,132,3,110
68,2,193,0,0,1,3.4,0,1,1,1,141,3,144
57,1,131,0,1,0,1.2,0,1,1,1,115,3,130
57,1,236,1,0,0,0.0,0,0,0,1,174,2,130

# Filtering

In [63]:
people

{'name': ['rohan', 'bablu', 'husen', 'mahesh'],
 'last': ['pol', 'pol', 'shaikh', 'jadhav'],
 'email': ['polrohan10@gmail.com',
  'poldhananjay20@gmil.com',
  'husen@gmial.com',
  'mahesh@gmail.com']}

In [64]:
dffff=pd.DataFrame(people)

In [65]:
dffff

     name    last                    email
0   rohan     pol     polrohan10@gmail.com
1   bablu     pol  poldhananjay20@gmil.com
2   husen  shaikh          husen@gmial.com
3  mahesh  jadhav         mahesh@gmail.com

In [66]:
fil=(dffff["last"]=="pol")

In [67]:
fil

0     True
1     True
2    False
3    False
Name: last, dtype: bool

In [68]:
dffff.loc[fil]

    name last                    email
0  rohan  pol     polrohan10@gmail.com
1  bablu  pol  poldhananjay20@gmil.com

In [69]:
dffff.loc[fil,["last","name"]]

  last   name
0  pol  rohan
1  pol  bablu

# and ,or filtering in pandas filter

# and-&

# or-|

In [70]:
# and
fil=((dffff["last"]=="pol")&(dffff["name"]=="rohan"))

In [71]:
fil

0     True
1    False
2    False
3    False
dtype: bool

In [72]:
dffff.loc[fil]

    name last                 email
0  rohan  pol  polrohan10@gmail.com

In [73]:
dffff.loc[fil,"name"]

0    rohan
Name: name, dtype: object

In [74]:
# or

In [75]:
filte=((dffff["last"]=="pol")|(dffff["name"]=="rohan"))

In [76]:
filte

0     True
1     True
2    False
3    False
dtype: bool

In [77]:
dffff.loc[filte]

    name last                    email
0  rohan  pol     polrohan10@gmail.com
1  bablu  pol  poldhananjay20@gmil.com

In [78]:
dffff.loc[filte,["name","email"]]

    name                    email
0  rohan     polrohan10@gmail.com
1  bablu  poldhananjay20@gmil.com

In [79]:
# not- ~
dffff.loc[~fil]

     name    last                    email
1   bablu     pol  poldhananjay20@gmil.com
2   husen  shaikh          husen@gmial.com
3  mahesh  jadhav         mahesh@gmail.com

In [80]:
dff

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [81]:
fil=(dff["age"]>53)

In [82]:
dff.loc[fil,"age"]

0      63
3      56
4      57
5      57
6      56
       ..
297    59
298    57
300    68
301    57
302    57
Name: age, Length: 175, dtype: int64

In [83]:
dff.loc[fil]

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [84]:
dff.value_counts("age")

age
58    19
57    17
54    16
59    14
52    13
51    12
62    11
60    11
44    11
56    11
41    10
64    10
63     9
67     9
65     8
55     8
61     8
53     8
45     8
43     8
42     8
50     7
66     7
48     7
46     7
49     5
47     5
70     4
39     4
68     4
35     4
69     3
40     3
38     3
71     3
37     2
34     2
76     1
29     1
74     1
77     1
dtype: int64

In [85]:
fil=((dff["age"]==58)|(dff["age"]==57))

In [86]:
dff.loc[fil]

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2,1
16,58,0,2,120,340,0,1,172,0,0.0,2,0,2,1
59,57,0,0,128,303,0,0,159,0,0.0,2,1,2,1
64,58,1,2,140,211,1,0,165,0,0.0,2,0,2,1
79,58,1,2,105,240,0,0,154,1,0.6,1,0,3,1
89,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
91,57,1,0,132,207,0,1,168,1,0.0,2,0,3,1
111,57,1,2,150,126,1,1,173,0,0.2,2,1,3,1
138,57,1,0,110,201,0,1,126,1,1.5,1,0,1,1
155,58,0,0,130,197,0,1,131,0,0.6,1,0,2,1
158,58,1,1,125,220,0,1,144,0,0.4,1,4,3,1
172,58,1,1,120,284,0,0,160,0,1.8,1,0,2,0
173,58,1,2,132,224,0,0,173,0,3.2,2,2,3,0
179,57,1,0,150,276,0,0,112,1,0.6,1,1,1,0
183,58,1,2,112,230,0,0,165,0,2.5,1,1,3,0
191,58,1,0,128,216,0,0,131,1,2.2,1,3,3,0
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3,0
210,57,1,2,128,229,0,0,150,0,0.4,1,1,3,0
231,57,1,0,165,289,1,0,124,0,1.0,1,3,3,0
236,58,1,0,125,300,0,0,171,0,0.0,2,2,3,0
243,57,1,0,152,274,0,1,88,1,1.2,1,1,3,0
256,58,1,0,128,259,0,0,130,1,3.0,1,2,3,0
273,58,1,0,100,234,0,1,156,0,0.1,2,1,3,0
276,58,1,0,146,218,0,1,105,0,2.0,1,1,3,0
277,57,1,1,124,261,0,1,141,0,0.3,2,0,3,0
278,58,0,1,136,319,1,0,152,0,0.0,2,2,2,0
287,57,1,1,154,232,0,0,164,0,0.0,2,1,2,0
288,57,1,0,110,335,0,1,143,1,3.0,1,1,3,0
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [87]:
people

{'name': ['rohan', 'bablu', 'husen', 'mahesh'],
 'last': ['pol', 'pol', 'shaikh', 'jadhav'],
 'email': ['polrohan10@gmail.com',
  'poldhananjay20@gmil.com',
  'husen@gmial.com',
  'mahesh@gmail.com']}

In [88]:
df

                     email    name    last
0     polrohan10@gmail.com   rohan     pol
1  poldhananjay20@gmil.com   bablu     pol
2          husen@gmial.com   husen  shaikh
3         mahesh@gmail.com  mahesh  jadhav

In [92]:
df.columns

Index(['email', 'name', 'last'], dtype='object')

# updating the columns

In [94]:
df.columns=["Email_","Name_","last_"]

In [96]:
df

                    Email_   Name_   last_
0     polrohan10@gmail.com   rohan     pol
1  poldhananjay20@gmil.com   bablu     pol
2          husen@gmial.com   husen  shaikh
3         mahesh@gmail.com  mahesh  jadhav

In [98]:
    # if we change the specific column that time use rename method

In [100]:
df.rename(columns={"Email_":"email"})

                     email   Name_   last_
0     polrohan10@gmail.com   rohan     pol
1  poldhananjay20@gmil.com   bablu     pol
2          husen@gmial.com   husen  shaikh
3         mahesh@gmail.com  mahesh  jadhav

In [106]:
df.rename(columns={"email":"email.com","Name_":"first name"},inplace=True)

In [108]:
df

                    Email_ first name   last_
0     polrohan10@gmail.com      rohan     pol
1  poldhananjay20@gmil.com      bablu     pol
2          husen@gmial.com      husen  shaikh
3         mahesh@gmail.com     mahesh  jadhav

In [110]:
# updating the specific row
df.loc[3]=["suchit","niranjan","suchit@123"]

In [112]:
df

                    Email_ first name       last_
0     polrohan10@gmail.com      rohan         pol
1  poldhananjay20@gmil.com      bablu         pol
2          husen@gmial.com      husen      shaikh
3                   suchit   niranjan  suchit@123

In [115]:
df.loc[3,["Email_","last_"]]=["suchit@123","suchit"]

In [117]:
df

                    Email_ first name   last_
0     polrohan10@gmail.com      rohan     pol
1  poldhananjay20@gmil.com      bablu     pol
2          husen@gmial.com      husen  shaikh
3               suchit@123   niranjan  suchit

In [119]:
# insert,add,delete

In [121]:
people

{'name': ['rohan', 'bablu', 'husen', 'mahesh'],
 'last': ['pol', 'pol', 'shaikh', 'jadhav'],
 'email': ['polrohan10@gmail.com',
  'poldhananjay20@gmil.com',
  'husen@gmial.com',
  'mahesh@gmail.com']}

In [123]:
df

                    Email_ first name   last_
0     polrohan10@gmail.com      rohan     pol
1  poldhananjay20@gmil.com      bablu     pol
2          husen@gmial.com      husen  shaikh
3               suchit@123   niranjan  suchit

In [134]:
df["full_name"]=df["first name"]+" "+df["last_"]

In [136]:
df

,Email_,first name,last_,rohan pol,bablu pol,husen shaikh,niranjan suchit,full_name
0,polrohan10@gmail.com,rohan,pol,rohan pol,bablu pol,husen shaikh,niranjan suchit,rohan pol
1,poldhananjay20@gmil.com,bablu,pol,rohan pol,bablu pol,husen shaikh,niranjan suchit,bablu pol
2,husen@gmial.com,husen,shaikh,rohan pol,bablu pol,husen shaikh,niranjan suchit,husen shaikh
3,suchit@123,niranjan,suchit,rohan pol,bablu pol,husen shaikh,niranjan suchit,niranjan suchit

In [137]:
df.drop(columns=["rohan pol","bablu pol","husen shaikh","niranjan suchit"],inplace=True)

In [139]:
df

                    Email_ first name   last_        full_name
0     polrohan10@gmail.com      rohan     pol        rohan pol
1  poldhananjay20@gmil.com      bablu     pol        bablu pol
2          husen@gmial.com      husen  shaikh     husen shaikh
3               suchit@123   niranjan  suchit  niranjan suchit

In [142]:
df["full_name"].str.split(" ")

0          [rohan, pol]
1          [bablu, pol]
2       [husen, shaikh]
3    [niranjan, suchit]
Name: full_name, dtype: object

In [144]:
df["full_name"].str.split(" ",expand=True)

          0       1
0     rohan     pol
1     bablu     pol
2     husen  shaikh
3  niranjan  suchit

In [148]:
df[["first name","last"]]=df["full_name"].str.split(" ",expand=True)

In [150]:
df

                    Email_ first name   last_        full_name    last
0     polrohan10@gmail.com      rohan     pol        rohan pol     pol
1  poldhananjay20@gmil.com      bablu     pol        bablu pol     pol
2          husen@gmial.com      husen  shaikh     husen shaikh  shaikh
3               suchit@123   niranjan  suchit  niranjan suchit  suchit

In [155]:
df=df.append({"first name":"diksha"},ignore_index=True)

C:\Users\polro\AppData\Local\Temp\ipykernel_15604\2534103082.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append({"first name":"diksha"},ignore_index=True)

In [157]:
df

                    Email_ first name   last_        full_name    last
0     polrohan10@gmail.com      rohan     pol        rohan pol     pol
1  poldhananjay20@gmil.com      bablu     pol        bablu pol     pol
2          husen@gmial.com      husen  shaikh     husen shaikh  shaikh
3               suchit@123   niranjan  suchit  niranjan suchit  suchit
4                      NaN     diksha     NaN              NaN     NaN
5                      NaN     diksha     NaN              NaN     NaN

In [159]:
df.drop(index=3,inplace=True)

KeyError: '[3] not found in axis'