In [1]:
import pandas as pd

# series

In [4]:
l=[11,22,33,44,55,66]
s=pd.Series(l)
print(s)
print()
x=pd.Series(l,index=["a","b","c","d","e","f"])
print(x)

0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64

a    11
b    22
c    33
d    44
e    55
f    66
dtype: int64

In [3]:
y=["rohan",69,55,7.5,"pol"]
series=pd.Series(y)
print(series)

0    rohan
1       69
2       55
3      7.5
4      pol
dtype: object

In [4]:
z=[1,2,3,4,5]
series_1=pd.Series(z,index=[1,2,3,4,5],dtype="float",name="python")
print(series_1)

1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
Name: python, dtype: float64

In [5]:


dict={"name":["java","python","c","c++"],"duration":[3,3,1,2],"rank":[3,2,1,2]}
series=pd.Series(dict)
print(series)
print(type(series))

name        [java, python, c, c++]
duration              [3, 3, 1, 2]
rank                  [3, 2, 1, 2]
dtype: object
<class 'pandas.core.series.Series'>

In [6]:
# addition
s1=pd.Series([11,22,33,44,55,66,77,88,99])
s2=pd.Series([2,3,4,4,3])
print(s1+s2)

0    13.0
1    25.0
2    37.0
3    48.0
4    58.0
5     NaN
6     NaN
7     NaN
8     NaN
dtype: float64

# DataFrame

In [7]:
l=[1,2,3,4,5,6,7,8,9]
df=pd.DataFrame(l,dtype="float")
print(df)
print(type(df))

     0
0  1.0
1  2.0
2  3.0
3  4.0
4  5.0
5  6.0
6  7.0
7  8.0
8  9.0
<class 'pandas.core.frame.DataFrame'>

In [8]:
dict={"name":["java","python","c","c++"],"duration":[2,3,1,2],"rate":[3,3,2,1]}
df=pd.DataFrame(dict)
print(df)
print()

     name  duration  rate
0    java         2     3
1  python         3     3
2       c         1     2
3     c++         2     1

In [9]:


dict={"name":["java","python","c","c++"],"duration":[12,11,10,9],"rating":[2,3,2,3]}
df=pd.DataFrame(dict,columns=["name"])
print(df)
print()
print(df["name"][3])

     name
0    java
1  python
2       c
3     c++

c++

In [10]:
list1=[[11,22,33,44,55],[1,2,3,4,5]]
df=pd.DataFrame(list1)
print(df)
print(type(df))

    0   1   2   3   4
0  11  22  33  44  55
1   1   2   3   4   5
<class 'pandas.core.frame.DataFrame'>

In [11]:
series={"a":pd.Series([1,2,3,4]),"b":pd.Series([33,44,55,66,77])}
df=pd.DataFrame(series)
print(df)

     a   b
0  1.0  33
1  2.0  44
2  3.0  55
3  4.0  66
4  NaN  77

In [12]:
import pandas as pd
dict2={"name":["Rohan","bablu","husen","mahesh"],"age":[21,23,24,23],"job":["no","yes","yes","yes"]}
df=pd.DataFrame(dict2)
print(df)
print()
particular_columns=pd.DataFrame(dict2,columns=["name","age"])
print(particular_columns)

     name  age  job
0   Rohan   21   no
1   bablu   23  yes
2   husen   24  yes
3  mahesh   23  yes

     name  age
0   Rohan   21
1   bablu   23
2   husen   24
3  mahesh   23

# Arithmetic operations

In [13]:
import pandas as pd
var=pd.DataFrame({"a":[1,2,3,4,5],"b":[5,6,8,4,2]})
var["add"]=var["a"]+var["b"]
var["sub"]=var["a"]-var["b"]
var["mul"]=var["a"]*var["b"]
var["div"]=var["a"]/var["b"]
var

   a  b  add  sub  mul       div
0  1  5    6   -4    5  0.200000
1  2  6    8   -4   12  0.333333
2  3  8   11   -5   24  0.375000
3  4  4    8    0   16  1.000000
4  5  2    7    3   10  2.500000

# logical conditions

In [14]:
students=pd.DataFrame({"name":["Rohan","husen","mahesh","bablu","suchit","sahil","omkar","tejas"
                              ,"shubham","nagraj","fayaz","nilesh","sahil","omkar"],
                      "surname":["pol","shaikh","jadhav","pol","niranjan","sikandar","nikam","zende",
                                "katkar","hunskatti","hangad","rugge","sikandar","powar"],
                      "age":[21,24,24,23,22,34,54,34,23,56,66,64,35,75]})
students

       name    surname  age
0     Rohan        pol   21
1     husen     shaikh   24
2    mahesh     jadhav   24
3     bablu        pol   23
4    suchit   niranjan   22
5     sahil   sikandar   34
6     omkar      nikam   54
7     tejas      zende   34
8   shubham     katkar   23
9    nagraj  hunskatti   56
10    fayaz     hangad   66
11   nilesh      rugge   64
12    sahil   sikandar   35
13    omkar      powar   75

In [15]:
students["above_30"]=students['age']>30
students

       name    surname  age  above_30
0     Rohan        pol   21     False
1     husen     shaikh   24     False
2    mahesh     jadhav   24     False
3     bablu        pol   23     False
4    suchit   niranjan   22     False
5     sahil   sikandar   34      True
6     omkar      nikam   54      True
7     tejas      zende   34      True
8   shubham     katkar   23     False
9    nagraj  hunskatti   56      True
10    fayaz     hangad   66      True
11   nilesh      rugge   64      True
12    sahil   sikandar   35      True
13    omkar      powar   75      True

# insert

In [16]:
students.insert(4,"city",["ashta","ashta","ashta","ashta","sangli","sangli","miraj","satara","goa",
                          "mumbai","pune","tasgao","karad","kolhapur"])

In [17]:
students

       name    surname  age  above_30      city
0     Rohan        pol   21     False     ashta
1     husen     shaikh   24     False     ashta
2    mahesh     jadhav   24     False     ashta
3     bablu        pol   23     False     ashta
4    suchit   niranjan   22     False    sangli
5     sahil   sikandar   34      True    sangli
6     omkar      nikam   54      True     miraj
7     tejas      zende   34      True    satara
8   shubham     katkar   23     False       goa
9    nagraj  hunskatti   56      True    mumbai
10    fayaz     hangad   66      True      pune
11   nilesh      rugge   64      True    tasgao
12    sahil   sikandar   35      True     karad
13    omkar      powar   75      True  kolhapur

# delete

In [18]:
students.pop("city")

0        ashta
1        ashta
2        ashta
3        ashta
4       sangli
5       sangli
6        miraj
7       satara
8          goa
9       mumbai
10        pune
11      tasgao
12       karad
13    kolhapur
Name: city, dtype: object

In [19]:
del students["city"]

KeyError: 'city'

In [20]:
print(students)

       name    surname  age  above_30
0     Rohan        pol   21     False
1     husen     shaikh   24     False
2    mahesh     jadhav   24     False
3     bablu        pol   23     False
4    suchit   niranjan   22     False
5     sahil   sikandar   34      True
6     omkar      nikam   54      True
7     tejas      zende   34      True
8   shubham     katkar   23     False
9    nagraj  hunskatti   56      True
10    fayaz     hangad   66      True
11   nilesh      rugge   64      True
12    sahil   sikandar   35      True
13    omkar      powar   75      True

# create csv file

In [21]:
students.to_csv("stuents")

# read csv

In [22]:
import pandas as pd

In [24]:
data=pd.read_csv("iris.csv")
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [25]:
data1=pd.read_csv('iris.csv',nrows=3)
data1

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [26]:
data2=pd.read_csv("iris.csv",usecols=["SepalLengthCm"])
print(data2)

     SepalLengthCm
0              5.1
1              4.9
2              4.7
3              4.6
4              5.0
..             ...
145            6.7
146            6.3
147            6.5
148            6.2
149            5.9

[150 rows x 1 columns]

In [27]:
data3=pd.read_csv("iris.csv",index_col=["Species"])
data3

                 Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa       1            5.1           3.5            1.4           0.2
Iris-setosa       2            4.9           3.0            1.4           0.2
Iris-setosa       3            4.7           3.2            1.3           0.2
Iris-setosa       4            4.6           3.1            1.5           0.2
Iris-setosa       5            5.0           3.6            1.4           0.2
...             ...            ...           ...            ...           ...
Iris-virginica  146            6.7           3.0            5.2           2.3
Iris-virginica  147            6.3           2.5            5.0           1.9
Iris-virginica  148            6.5           3.0            5.2           2.0
Iris-virginica  149            6.2           3.4            5.4           2.3
Iris-virginica  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [28]:
data4=pd.read_csv("iris.csv",header=1)
data4

       1  5.1  3.5  1.4  0.2     Iris-setosa
0      2  4.9  3.0  1.4  0.2     Iris-setosa
1      3  4.7  3.2  1.3  0.2     Iris-setosa
2      4  4.6  3.1  1.5  0.2     Iris-setosa
3      5  5.0  3.6  1.4  0.2     Iris-setosa
4      6  5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...  ...             ...
144  146  6.7  3.0  5.2  2.3  Iris-virginica
145  147  6.3  2.5  5.0  1.9  Iris-virginica
146  148  6.5  3.0  5.2  2.0  Iris-virginica
147  149  6.2  3.4  5.4  2.3  Iris-virginica
148  150  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 6 columns]

In [29]:
data5=pd.read_csv("iris.csv",names=["id","slc","swc","plc","pwc","species"])
data5

,id,slc,swc,plc,pwc,species
0,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,1,5.1,3.5,1.4,0.2,Iris-setosa
2,2,4.9,3.0,1.4,0.2,Iris-setosa
3,3,4.7,3.2,1.3,0.2,Iris-setosa
4,4,4.6,3.1,1.5,0.2,Iris-setosa
...,...,...,...,...,...,...
146,146,6.7,3.0,5.2,2.3,Iris-virginica
147,147,6.3,2.5,5.0,1.9,Iris-virginica
148,148,6.5,3.0,5.2,2.0,Iris-virginica
149,149,6.2,3.4,5.4,2.3,Iris-virginica
150,150,5.9,3.0,5.1,1.8,Iris-virginica

In [30]:
data6=pd.read_csv("iris.csv",dtype={"Id":float,"SepalLengthCm":float})
data6

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1.0,5.1,3.5,1.4,0.2,Iris-setosa
1,2.0,4.9,3.0,1.4,0.2,Iris-setosa
2,3.0,4.7,3.2,1.3,0.2,Iris-setosa
3,4.0,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,3.0,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
data4=pd.read_csv("iris.csv")
data4

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [36]:
data4.index

RangeIndex(start=0, stop=150, step=1)

In [37]:
data4.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [39]:
data4.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [42]:
data4.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [50]:
data4.tail(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [51]:
data4[:20]

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa

In [55]:
type(data4)

pandas.core.frame.DataFrame

In [57]:
data4.index.array

<PandasArray>
[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
 ...
 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]
Length: 150, dtype: int64

In [61]:
import numpy as np
numpyarray=np.asarray(data4)
numpyarray

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [6, 5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [8, 5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [9, 4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [10, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [11, 5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [12, 4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [13, 4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [14, 4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [15, 5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [16, 5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [17, 5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [18, 5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [20, 5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [21, 5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [22, 5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [23, 4.6, 3.6, 1.0, 0.2, 'Iris-setosa'],
       [24, 5.1, 3.3, 1.7, 0.5, 'Iris-setosa'],
       [25, 4.8, 3.4, 1.9, 0.2, 'Iris-setosa'],
       [26, 5.0, 3.0, 1.6, 0.2, 'Iris-setosa'],
       [27, 5.0, 3.4, 1.6, 0.4, 'Iris-setosa'],
       [28, 5.2, 3.5, 1.5, 0.2, 'Iris-setosa'],
       [29, 5.2, 3.4, 1.4, 0.2, 'Iris-setosa'],
       [30, 4.7, 3.2, 1.6, 0.2, 'Iris-setosa'],
       [31, 4.8, 3.1, 1.6, 0.2, 'Iris-setosa'],
       [32, 5.4, 3.4, 1.5, 0.4, 'Iris-setosa'],
       [33, 5.2, 4.1, 1.5, 0.1, 'Iris-setosa'],
       [34, 5.5, 4.2, 1.4, 0.2, 'Iris-setosa'],
       [35, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [36, 5.0, 3.2, 1.2, 0.2, 'Iris-setosa'],
       [37, 5.5, 3.5, 1.3, 0.2, 'Iris-setosa'],
       [38, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [39, 4.4, 3.0, 1.3, 0.2, 'Iris-setosa'],
       [40, 5.1, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [41, 5.0, 3.5, 1.3, 0.3, 'Iris-setosa'],
       [42, 4.5, 2.3, 1.3, 0.3, 'Iris-setosa'],
       [43, 4.4, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [44, 5.0, 3.5, 1.6, 0.6, 'Iris-setosa'],
       [45, 5.1, 3.8, 1.9, 0.4, 'Iris-setosa'],
       [46, 4.8, 3.0, 1.4, 0.3, 'Iris-setosa'],
       [47, 5.1, 3.8, 1.6, 0.2, 'Iris-setosa'],
       [48, 4.6, 3.2, 1.4, 0.2, 'Iris-setosa'],
       [49, 5.3, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [50, 5.0, 3.3, 1.4, 0.2, 'Iris-setosa'],
       [51, 7.0, 3.2, 4.7, 1.4, 'Iris-versicolor'],
       [52, 6.4, 3.2, 4.5, 1.5, 'Iris-versicolor'],
       [53, 6.9, 3.1, 4.9, 1.5, 'Iris-versicolor'],
       [54, 5.5, 2.3, 4.0, 1.3, 'Iris-versicolor'],
       [55, 6.5, 2.8, 4.6, 1.5, 'Iris-versicolor'],
       [56, 5.7, 2.8, 4.5, 1.3, 'Iris-versicolor'],
       [57, 6.3, 3.3, 4.7, 1.6, 'Iris-versicolor'],
       [58, 4.9, 2.4, 3.3, 1.0, 'Iris-versicolor'],
       [59, 6.6, 2.9, 4.6, 1.3, 'Iris-versicolor'],
       [60, 5.2, 2.7, 3.9, 1.4, 'Iris-versicolor'],
       [61, 5.0, 2.0, 3.5, 1.0, 'Iris-versicolor'],
       [62, 5.9, 3.0, 4.2, 1.5, 'Iris-versicolor'],
       [63, 6.0, 2.2, 4.0, 1.0, 'Iris-versicolor'],
       [64, 6.1, 2.9, 4.7, 1.4, 'Iris-versicolor'],
       [65, 5.6, 2.9, 3.6, 1.3, 'Iris-versicolor'],
       [66, 6.7, 3.1, 4.4, 1.4, 'Iris-versicolor'],
       [67, 5.6, 3.0, 4.5, 1.5, 'Iris-versicolor'],
       [68, 5.8, 2.7, 4.1, 1.0, 'Iris-versicolor'],
       [69, 6.2, 2.2, 4.5, 1.5, 'Iris-versicolor'],
       [70, 5.6, 2.5, 3.9, 1.1, 'Iris-versicolor'],
       [71, 5.9, 3.2, 4.8, 1.8, 'Iris-versicolor'],
       [72, 6.1, 2.8, 4.0, 1.3, 'Iris-versicolor'],
       [73, 6.3, 2.5, 4.9, 1.5, 'Iris-versicolor'],
       [74, 6.1, 2.8, 4.7, 1.2, 'Iris-versicolor'],
       [75, 6.4, 2.9, 4.3, 1.3, 'Iris-versicolor'],
       [76, 6.6, 3.0, 4.4, 1.4, 'Iris-versicolor'],
       [77, 6.8, 2.8, 4.8, 1.4, 'Iris-versicolor'],
       [78, 6.7, 3.0, 5.0, 1.7, 'Iris-versicolor'],
       [79, 6.0, 2.9, 4.5, 1.5, 'Iris-versicolor'],
       [80, 5.7, 2.6, 3.5, 1.0, 'Iris-versicolor'],
       [81, 5.5, 2.4, 3.8, 1.1, 'Iris-versicolor'],
       [82, 5.5, 2.4, 3.7, 1.0, 'Iris-versicolor'],
       [83, 5.8, 2.7, 3.9, 1.2, 'Iris-versicolor'],
       [84, 6.0, 2.7, 5.1, 1.6, 'Iris-versicolor'],
       [85, 5.4, 3.0, 4.5, 1.5, 'Iris-versicolor'],
       [86, 6.0, 3.4, 4.5, 1.6, 'Iris-versicolor'],
       [87, 6.7, 3.1, 4.7, 1.5, 'Iris-versicolor'],
       [88, 6.3, 2.3, 4.4, 1.3, 'Iris-versicolor'],
       [89, 5.6, 3.0, 4.1, 1.3, 'Iris-versicolor'],
       [90, 5.5, 2.5, 4.0, 1.3, 'Iris-versicolor'],
       [91, 5.5, 2.6, 4.4, 1.2, 'Iris-versicolor'],
       [92, 6.1, 3.0, 4.6, 1.4, 'Iris-versicolor'],
       [93, 5.8, 2.6, 4.0, 1.2, 'Iris-versicolor'],
       [94, 5.0, 2.3, 3.3, 1.0, 'Iris-versicolor'],
       [95, 5.6, 2.7, 4.2, 1.3, 'Iris-versicolor'],
       [96, 5.7, 3.0, 4.2, 1.2, 'Iris-versicolor'],
       [97, 5.7, 2.9, 4.2, 1.3, 'Iris-versicolor'],
       [98, 6.2, 2.9, 4.3, 1.3, 'Iris-versicolor'],
       [99, 5.1, 2.5, 3.0, 1.1, 'Iris-versicolor'],
       [100, 5.7, 2.8, 4.1, 1.3, 'Iris-versicolor'],
       [101, 6.3, 3.3, 6.0, 2.5, 'Iris-virginica'],
       [102, 5.8, 2.7, 5.1, 1.9, 'Iris-virginica'],
       [103, 7.1, 3.0, 5.9, 2.1, 'Iris-virginica'],
       [104, 6.3, 2.9, 5.6, 1.8, 'Iris-virginica'],
       [105, 6.5, 3.0, 5.8, 2.2, 'Iris-virginica'],
       [106, 7.6, 3.0, 6.6, 2.1, 'Iris-virginica'],
       [107, 4.9, 2.5, 4.5, 1.7, 'Iris-virginica'],
       [108, 7.3, 2.9, 6.3, 1.8, 'Iris-virginica'],
       [109, 6.7, 2.5, 5.8, 1.8, 'Iris-virginica'],
       [110, 7.2, 3.6, 6.1, 2.5, 'Iris-virginica'],
       [111, 6.5, 3.2, 5.1, 2.0, 'Iris-virginica'],
       [112, 6.4, 2.7, 5.3, 1.9, 'Iris-virginica'],
       [113, 6.8, 3.0, 5.5, 2.1, 'Iris-virginica'],
       [114, 5.7, 2.5, 5.0, 2.0, 'Iris-virginica'],
       [115, 5.8, 2.8, 5.1, 2.4, 'Iris-virginica'],
       [116, 6.4, 3.2, 5.3, 2.3, 'Iris-virginica'],
       [117, 6.5, 3.0, 5.5, 1.8, 'Iris-virginica'],
       [118, 7.7, 3.8, 6.7, 2.2, 'Iris-virginica'],
       [119, 7.7, 2.6, 6.9, 2.3, 'Iris-virginica'],
       [120, 6.0, 2.2, 5.0, 1.5, 'Iris-virginica'],
       [121, 6.9, 3.2, 5.7, 2.3, 'Iris-virginica'],
       [122, 5.6, 2.8, 4.9, 2.0, 'Iris-virginica'],
       [123, 7.7, 2.8, 6.7, 2.0, 'Iris-virginica'],
       [124, 6.3, 2.7, 4.9, 1.8, 'Iris-virginica'],
       [125, 6.7, 3.3, 5.7, 2.1, 'Iris-virginica'],
       [126, 7.2, 3.2, 6.0, 1.8, 'Iris-virginica'],
       [127, 6.2, 2.8, 4.8, 1.8, 'Iris-virginica'],
       [128, 6.1, 3.0, 4.9, 1.8, 'Iris-virginica'],
       [129, 6.4, 2.8, 5.6, 2.1, 'Iris-virginica'],
       [130, 7.2, 3.0, 5.8, 1.6, 'Iris-virginica'],
       [131, 7.4, 2.8, 6.1, 1.9, 'Iris-virginica'],
       [132, 7.9, 3.8, 6.4, 2.0, 'Iris-virginica'],
       [133, 6.4, 2.8, 5.6, 2.2, 'Iris-virginica'],
       [134, 6.3, 2.8, 5.1, 1.5, 'Iris-virginica'],
       [135, 6.1, 2.6, 5.6, 1.4, 'Iris-virginica'],
       [136, 7.7, 3.0, 6.1, 2.3, 'Iris-virginica'],
       [137, 6.3, 3.4, 5.6, 2.4, 'Iris-virginica'],
       [138, 6.4, 3.1, 5.5, 1.8, 'Iris-virginica'],
       [139, 6.0, 3.0, 4.8, 1.8, 'Iris-virginica'],
       [140, 6.9, 3.1, 5.4, 2.1, 'Iris-virginica'],
       [141, 6.7, 3.1, 5.6, 2.4, 'Iris-virginica'],
       [142, 6.9, 3.1, 5.1, 2.3, 'Iris-virginica'],
       [143, 5.8, 2.7, 5.1, 1.9, 'Iris-virginica'],
       [144, 6.8, 3.2, 5.9, 2.3, 'Iris-virginica'],
       [145, 6.7, 3.3, 5.7, 2.5, 'Iris-virginica'],
       [146, 6.7, 3.0, 5.2, 2.3, 'Iris-virginica'],
       [147, 6.3, 2.5, 5.0, 1.9, 'Iris-virginica'],
       [148, 6.5, 3.0, 5.2, 2.0, 'Iris-virginica'],
       [149, 6.2, 3.4, 5.4, 2.3, 'Iris-virginica'],
       [150, 5.9, 3.0, 5.1, 1.8, 'Iris-virginica']], dtype=object)

In [68]:
data4.sort_index(axis=0,ascending=False)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
149,150,5.9,3.0,5.1,1.8,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
...,...,...,...,...,...,...
4,5,5.0,3.6,1.4,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
0,1,5.1,3.5,1.4,0.2,Iris-setosa

In [71]:
data4.loc[0,"Species"]="python"
data4

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,python
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [72]:
data4.loc[[3,6],["PetalWidthCm","Species"]]

   PetalWidthCm      Species
3           0.2  Iris-setosa
6           0.3  Iris-setosa

In [6]:
import pandas as np
data4.loc[:,["Id","SepalLengthCm"]]

      Id  SepalLengthCm
0      1            5.1
1      2            4.9
2      3            4.7
3      4            4.6
4      5            5.0
..   ...            ...
145  146            6.7
146  147            6.3
147  148            6.5
148  149            6.2
149  150            5.9

[150 rows x 2 columns]

In [11]:
data4.iloc[0:3,5]

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
Name: Species, dtype: object

In [13]:
data4.drop("SepalLengthCm",axis=1)

      Id  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1           3.5            1.4           0.2     Iris-setosa
1      2           3.0            1.4           0.2     Iris-setosa
2      3           3.2            1.3           0.2     Iris-setosa
3      4           3.1            1.5           0.2     Iris-setosa
4      5           3.6            1.4           0.2     Iris-setosa
..   ...           ...            ...           ...             ...
145  146           3.0            5.2           2.3  Iris-virginica
146  147           2.5            5.0           1.9  Iris-virginica
147  148           3.0            5.2           2.0  Iris-virginica
148  149           3.4            5.4           2.3  Iris-virginica
149  150           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [14]:
data4.drop(3,axis=0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

# handling missiong values

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("test.csv")

In [4]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [6]:
data.index

RangeIndex(start=0, stop=1459, step=1)

In [9]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

In [10]:
data.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [13]:
#data.dropna()
data.dropna(axis=1)
#data.dropna(how="any")
#data.dropna(how="all")

,Id,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition
0,1461,20,11622,Pave,Reg,Lvl,Inside,Gtl,NAmes,Feedr,...,140,0,0,0,120,0,0,6,2010,Normal
1,1462,20,14267,Pave,IR1,Lvl,Corner,Gtl,NAmes,Norm,...,393,36,0,0,0,0,12500,6,2010,Normal
2,1463,60,13830,Pave,IR1,Lvl,Inside,Gtl,Gilbert,Norm,...,212,34,0,0,0,0,0,3,2010,Normal
3,1464,60,9978,Pave,IR1,Lvl,Inside,Gtl,Gilbert,Norm,...,360,36,0,0,0,0,0,6,2010,Normal
4,1465,120,5005,Pave,IR1,HLS,Inside,Gtl,StoneBr,Norm,...,0,82,0,0,144,0,0,1,2010,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,1936,Pave,Reg,Lvl,Inside,Gtl,MeadowV,Norm,...,0,0,0,0,0,0,0,6,2006,Normal
1455,2916,160,1894,Pave,Reg,Lvl,Inside,Gtl,MeadowV,Norm,...,0,24,0,0,0,0,0,4,2006,Abnorml
1456,2917,20,20000,Pave,Reg,Lvl,Inside,Gtl,Mitchel,Norm,...,474,0,0,0,0,0,0,9,2006,Abnorml
1457,2918,85,10441,Pave,Reg,Lvl,Inside,Gtl,Mitchel,Norm,...,80,32,0,0,0,0,700,7,2006,Normal
1458,2919,60,9627,Pave,Reg,Lvl,Inside,Mod,Mitchel,Norm,...,190,48,0,0,0,0,0,11,2006,Normal

In [17]:
data.dropna(subset=["LotShape"])

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [18]:
data.dropna(inplace=True)

In [19]:
data

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition]
Index: []

[0 rows x 80 columns]

In [20]:
data

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition]
Index: []

[0 rows x 80 columns]

In [53]:
data2=pd.read_csv("Data.csv")

In [75]:
data2.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain        48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0
5   France  35.0  58000.0       Yes

In [76]:
data2.tail()

   Country   Age   Salary Purchased
3    Spain  38.0  61000.0
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [77]:
data2.index

Int64Index([0, 1, 2, 3, 5, 7, 8, 9], dtype='int64')

In [78]:
data2.dropna()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain        48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [79]:
data2.dropna(axis=1)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain        48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [80]:
data2.dropna(thresh=1)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain        48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [81]:
data2.iloc[4,0]=""

In [82]:
data2.iloc[1,1]=""

In [83]:
data2.loc[3,"Purchased"]=""

In [84]:
data2

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain        48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0
5           35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [86]:
data2.fillna("python")

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain        48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0
5           35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes