# removing duplicates

In [3]:
import pandas as pd

In [5]:
data=pd.read_csv('datasets/student_admission_record.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/student_admission_record.csv'

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    147 non-null    object
 1   Age                     147 non-null    float64
 2   Gender                  147 non-null    object
 3   Admission Test Score    146 non-null    float64
 4   High School Percentage  146 non-null    float64
 5   City                    147 non-null    object
 6   Admission Status        147 non-null    object
dtypes: float64(3), object(4)
memory usage: 8.7+ KB

In [19]:
data.describe()

              Age  Admission Test Score  High School Percentage
count  147.000000            146.000000              146.000000
mean    19.680272             77.657534               75.684726
std      4.540512             16.855343               17.368014
min     -1.000000             -5.000000              -10.000000
25%     18.000000             68.250000               65.052500
50%     20.000000             79.000000               77.545000
75%     22.000000             89.000000               88.312500
max     24.000000            150.000000              110.500000

# detecting duplicates

In [20]:
# check for duplicates
duplicated=data.duplicated().sum()
duplicated

6

In [21]:
# show all duplicated rows
data[data.duplicated()]

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
22,Kamran,18.0,Male,53.0,98.98,Multan,Rejected
52,Ahmed,21.0,Male,62.0,79.03,Karachi,Accepted
88,Aliya,17.0,Male,55.0,85.29,Karachi,Rejected
110,Hamza,22.0,Male,99.0,86.58,Multan,Accepted
120,Ayesha,24.0,Male,94.0,98.43,Multan,Rejected
122,Tuba,17.0,Female,75.0,78.43,Peshawar,Accepted

In [25]:
# find the duplicates based on specific columns
data[data.duplicated(subset=['Name','Gender','High School Percentage'])]

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
22,Kamran,18.0,Male,53.0,98.98,Multan,Rejected
43,Waqar,21.0,Female,99.0,60.73,Karachi,Accepted
52,Ahmed,21.0,Male,62.0,79.03,Karachi,Accepted
81,Lubna,NaN,Female,89.0,82.57,Multan,Rejected
88,Aliya,17.0,Male,55.0,85.29,Karachi,Rejected
96,Muneera,19.0,Female,NaN,67.75,Karachi,Rejected
109,Mehwish,18.0,Female,72.0,67.51,NaN,Accepted
110,Hamza,22.0,Male,99.0,86.58,Multan,Accepted
120,Ayesha,24.0,Male,94.0,98.43,Multan,Rejected
122,Tuba,17.0,Female,75.0,78.43,Peshawar,Accepted
140,Feroze,23.0,Female,51.0,92.36,Rawalpindi,Accepted
141,Laiba,21.0,Female,76.0,NaN,Karachi,Rejected

# removing duplicates

In [26]:
# remove all duplicates
data.drop_duplicates(inplace=True)

In [29]:
# remove duplicates based on specific columns
data.drop_duplicates(subset=['Name','Gender','High School Percentage'],inplace=True)

In [30]:
# remove duplicates and keep last occurance
data.drop_duplicates(keep='last')

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,Shehroz,24.0,Female,50.0,68.90,Quetta,Rejected
1,Waqar,21.0,Female,99.0,60.73,Karachi,NaN
2,Bushra,17.0,Male,89.0,NaN,Islamabad,Accepted
3,Aliya,17.0,Male,55.0,85.29,Karachi,Rejected
4,Bilal,20.0,Male,65.0,61.13,Lahore,NaN
...,...,...,...,...,...,...,...
152,Ali,19.0,Female,85.0,78.09,Quetta,Accepted
153,Bilal,17.0,Female,81.0,84.40,Islamabad,Rejected
154,Fatima,21.0,Female,98.0,50.86,Multan,Accepted
155,Shoaib,-1.0,Male,91.0,80.12,Quetta,Accepted
156,Maaz,17.0,Male,88.0,86.85,Lahore,Accepted

## revising the concepts

In [6]:
import pandas as pd
data=pd.read_csv('F:/pol/06 data preprocessing/datasets/student_admission_record.csv')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    147 non-null    object
 1   Age                     147 non-null    float64
 2   Gender                  147 non-null    object
 3   Admission Test Score    146 non-null    float64
 4   High School Percentage  146 non-null    float64
 5   City                    147 non-null    object
 6   Admission Status        147 non-null    object
dtypes: float64(3), object(4)
memory usage: 8.7+ KB

In [11]:
data.duplicated().sum()

6

In [17]:
data.drop_duplicates(inplace=True)

In [18]:
data.duplicated().sum()

0