# fixing inconsistent data

In [55]:
import pandas as pd
import numpy as np

data = {
    'Customer_ID': [101, 102, 103, 104, 105],
    'Name': [' Alice ', 'BOB', 'Charlie', 'dAvId', 'Eve'],
    'Date_of_Birth': ['12/03/1995', '1995-03-12', '03-12-1995', '1995/03/12', 'March 12, 1995'],
    'Amount_Spent': ['$500', '600$', '700', '800USD', '900'],
    'Country': ['usa', 'USA ', 'U.S.A.', 'usA', 'United States'],
    'Phone_Number': ['+1 123 456 7890', '123-456-7890', '(123) 456-7890', '1234567890', '+1-123-456-7890']
}

data = pd.DataFrame(data)
data

,Customer_ID,Name,Date_of_Birth,Amount_Spent,Country,Phone_Number
0,101,Alice,12/03/1995,$500,usa,+1 123 456 7890
1,102,BOB,1995-03-12,600$,USA,123-456-7890
2,103,Charlie,03-12-1995,700,U.S.A.,(123) 456-7890
3,104,dAvId,1995/03/12,800USD,usA,1234567890
4,105,Eve,"March 12, 1995",900,United States,+1-123-456-7890

# 1) standardizing formate

a) convert date formates to standard format

In [56]:
data['Date_of_Birth']=pd.to_datetime(data['Date_of_Birth'],errors='coerce').dt.strftime('%y-%m-%d')

In [57]:
data

,Customer_ID,Name,Date_of_Birth,Amount_Spent,Country,Phone_Number
0,101,Alice,95-12-03,$500,usa,+1 123 456 7890
1,102,BOB,95-03-12,600$,USA,123-456-7890
2,103,Charlie,95-03-12,700,U.S.A.,(123) 456-7890
3,104,dAvId,95-03-12,800USD,usA,1234567890
4,105,Eve,95-03-12,900,United States,+1-123-456-7890

b) convert currency to numeric values

In [66]:
data['Amount_Spent']=data['Amount_Spent'].replace({'$':'','USD':'',',':''},regex=True).astype(float)

In [67]:
data

,Customer_ID,Name,Date_of_Birth,Amount_Spent,Country,Phone_Number
0,101,Alice,95-12-03,500.0,usa,+1 123 456 7890
1,102,BOB,95-03-12,600.0,USA,123-456-7890
2,103,Charlie,95-03-12,700.0,U.S.A.,(123) 456-7890
3,104,dAvId,95-03-12,800.0,usA,1234567890
4,105,Eve,95-03-12,900.0,United States,+1-123-456-7890

# correcting the types

a) standardise the names

In [74]:
data['Country']=df['Country'].str.strip().str.lower().replace({
    'usa':'united state',
    'USA':'united state',
    'U.S.A.':'united state',
    'usA':'united state',
    'United States': 'united state'    
})
data

,Customer_ID,Name,Date_of_Birth,Amount_Spent,Country,Phone_Number
0,101,Alice,95-12-03,500.0,united state,+1 123 456 7890
1,102,BOB,95-03-12,600.0,united state,123-456-7890
2,103,Charlie,95-03-12,700.0,u.s.a.,(123) 456-7890
3,104,dAvId,95-03-12,800.0,united state,1234567890
4,105,Eve,95-03-12,900.0,united states,+1-123-456-7890

b) handling case sensetive

In [78]:
data['Name']=data['Name'].str.strip().str.title() # remove spaces and convert to title case
data

,Customer_ID,Name,Date_of_Birth,Amount_Spent,Country,Phone_Number
0,101,Alice,95-12-03,500.0,united state,+1 123 456 7890
1,102,Bob,95-03-12,600.0,united state,123-456-7890
2,103,Charlie,95-03-12,700.0,u.s.a.,(123) 456-7890
3,104,David,95-03-12,800.0,united state,1234567890
4,105,Eve,95-03-12,900.0,united states,+1-123-456-7890

In [80]:
data['Country']=data['Country'].str.strip() # removing the extra space
data

,Customer_ID,Name,Date_of_Birth,Amount_Spent,Country,Phone_Number
0,101,Alice,95-12-03,500.0,united state,+1 123 456 7890
1,102,Bob,95-03-12,600.0,united state,123-456-7890
2,103,Charlie,95-03-12,700.0,u.s.a.,(123) 456-7890
3,104,David,95-03-12,800.0,united state,1234567890
4,105,Eve,95-03-12,900.0,united states,+1-123-456-7890

# Ensuring  data type consistency

In [86]:
# remove non numeric characters
data['Phone_Number']=data['Phone_Number'].str.replace(r'\D',"")
data

C:\Users\polro\AppData\Local\Temp\ipykernel_2692\284843748.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  data['Phone_Number']=data['Phone_Number'].str.replace(r'\D',"")

,Customer_ID,Name,Date_of_Birth,Amount_Spent,Country,Phone_Number
0,101,Alice,95-12-03,500.0,united state,11234567890
1,102,Bob,95-03-12,600.0,united state,1234567890
2,103,Charlie,95-03-12,700.0,u.s.a.,1234567890
3,104,David,95-03-12,800.0,united state,1234567890
4,105,Eve,95-03-12,900.0,united states,11234567890