In [1]:
import pandas as pd
import numpy as np

data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Birth_Date': ['2000-05-10', '2025-01-15', '1980-07-20', '1995-12-05', '1890-06-30'],  # 2025 is invalid, 1890 is too old
    'Salary': [50000, -1000, 70000, 80000, 3000000],  # Negative salary, extremely high value
    'Department': ['HR', 'IT', 'Finance', 'Unknown', 'Marketing'],  # 'Unknown' is an invalid department
    'Country': ['USA', 'India', 'Germany', 'UAE', 'Mars']  # 'Mars' is an invalid country
}

df = pd.DataFrame(data)

df

   Employee_ID     Name  Birth_Date   Salary Department  Country
0          101    Alice  2000-05-10    50000         HR      USA
1          102      Bob  2025-01-15    -1000         IT    India
2          103  Charlie  1980-07-20    70000    Finance  Germany
3          104    David  1995-12-05    80000    Unknown      UAE
4          105      Eve  1890-06-30  3000000  Marketing     Mars

# Methods to handle incorrect or invalid data

# 1) cross validatation ( checking logical consistency)

a) verify birth dates

In [3]:
from datetime import datetime
df['Birth_Date']=pd.to_datetime(df['Birth_Date'],errors='coerce')
min_date=datetime(1920,1,1)
max_date=datetime.today()

df.iloc[(df['Birth_Date']<min_date)|(df['Birth_Date']>max_date)]=np.nan
df

   Employee_ID     Name Birth_Date   Salary Department  Country
0        101.0    Alice 2000-05-10  50000.0         HR      USA
1        102.0      Bob 2025-01-15  -1000.0         IT    India
2        103.0  Charlie 1980-07-20  70000.0    Finance  Germany
3        104.0    David 1995-12-05  80000.0    Unknown      UAE
4          NaN      NaN        NaT      NaN        NaN      NaN

b) domain specific rules

In [4]:
# define salary limits
df.iloc[(df['Salary']<6000)|(df['Salary']>75000)]=np.nan
df

   Employee_ID     Name Birth_Date   Salary Department  Country
0        101.0    Alice 2000-05-10  50000.0         HR      USA
1          NaN      NaN        NaT      NaN        NaN      NaN
2        103.0  Charlie 1980-07-20  70000.0    Finance  Germany
3          NaN      NaN        NaT      NaN        NaN      NaN
4          NaN      NaN        NaT      NaN        NaN      NaN

# reference data check

In [9]:
valid_departments = ['HR', 'IT', 'Finance', 'Marketing', 'Operations', 'Sales']
df.loc[~df['Department'].isin(valid_departments)]=np.nan
df

   Employee_ID Name Birth_Date  Salary Department Country
0          NaN  NaN        NaT     NaN        NaN     NaN
1          NaN  NaN        NaT     NaN        NaN     NaN
2          NaN  NaN        NaT     NaN        NaN     NaN
3          NaN  NaN        NaT     NaN        NaN     NaN
4          NaN  NaN        NaT     NaN        NaN     NaN

# Handling missing or incorrect data

In [7]:
data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Birth_Date': ['2000-05-10', '2025-01-15', '1980-07-20', '1995-12-05', '1890-06-30'],  # 2025 is invalid, 1890 is too old
    'Salary': [50000, -1000, 70000, 80000, 3000000],  # Negative salary, extremely high value
    'Department': ['HR', 'IT', 'Finance', 'Unknown', 'Marketing'],  # 'Unknown' is an invalid department
    'Country': ['USA', 'India', 'Germany', 'UAE', 'Mars']  # 'Mars' is an invalid country
}

df = pd.DataFrame(data)

df

   Employee_ID     Name  Birth_Date   Salary Department  Country
0          101    Alice  2000-05-10    50000         HR      USA
1          102      Bob  2025-01-15    -1000         IT    India
2          103  Charlie  1980-07-20    70000    Finance  Germany
3          104    David  1995-12-05    80000    Unknown      UAE
4          105      Eve  1890-06-30  3000000  Marketing     Mars

In [8]:
df['Birth_Date'].fillna('unknown',inplace=True) # filling missing value

In [9]:
# replace invalid salary with median 
df['Salary'].fillna((df['Salary']<0).median(),inplace=True)

In [10]:
df

   Employee_ID     Name  Birth_Date   Salary Department  Country
0          101    Alice  2000-05-10    50000         HR      USA
1          102      Bob  2025-01-15    -1000         IT    India
2          103  Charlie  1980-07-20    70000    Finance  Germany
3          104    David  1995-12-05    80000    Unknown      UAE
4          105      Eve  1890-06-30  3000000  Marketing     Mars

In [11]:
# assign default departement
df['Department'].fillna('General',inplace=True)
df

   Employee_ID     Name  Birth_Date   Salary Department  Country
0          101    Alice  2000-05-10    50000         HR      USA
1          102      Bob  2025-01-15    -1000         IT    India
2          103  Charlie  1980-07-20    70000    Finance  Germany
3          104    David  1995-12-05    80000    Unknown      UAE
4          105      Eve  1890-06-30  3000000  Marketing     Mars