In [2]:
import pandas as pd

data = {
    'Customer_ID': [101, 102, 103, 104, 105],
    'City': ['NY', 'New York', 'new york', 'Los Angeles', 'LA'],  # Inconsistent city names
    'Subscription_Type': ['Basic', 'Premium', 'basic', 'VIP', 'vip'],  # Different case
    'Payment_Method': ['Credit Card', 'Paypal', 'credit card', 'paypal', 'Cash'],  # Different formats
    'Gender': ['Male', 'Female', 'M', 'F', 'Other']  # Different labels for the same category
}

df = pd.DataFrame(data)
df

   Customer_ID         City Subscription_Type Payment_Method  Gender
0          101           NY             Basic    Credit Card    Male
1          102     New York           Premium         Paypal  Female
2          103     new york             basic    credit card       M
3          104  Los Angeles               VIP         paypal       F
4          105           LA               vip           Cash   Other

# Merging similar categories

a) standardizing city names

In [17]:
df['City']=df['City'].str.lower().replace({'new York':'new york',
                                  'new york': 'new york',
                                  'ny':'new york',
                                  'los angeles': 'los angeles',
                                  'la':'los angeles'
                                 })
df

   Customer_ID         City Subscription_Type Payment_Method  Gender
0          101     new york             Basic    Credit Card    Male
1          102     new york           Premium         Paypal  Female
2          103     new york             basic    credit card       M
3          104  los angeles               VIP         paypal       F
4          105  los angeles               vip           Cash   Other

b) standardizing subscription type

In [20]:
df['Subscription_Type']=df['Subscription_Type'].str.lower().replace({'basic':'basic',
                                                                    'premium':'premium',
                                                                    'vip':'vip'})
df

   Customer_ID         City Subscription_Type Payment_Method  Gender
0          101     new york             basic    Credit Card    Male
1          102     new york           premium         Paypal  Female
2          103     new york             basic    credit card       M
3          104  los angeles               vip         paypal       F
4          105  los angeles               vip           Cash   Other

   Customer_ID         City Subscription_Type Payment_Method  Gender
0          101     new york             basic    Credit Card    Male
1          102     new york           premium         Paypal  Female
2          103     new york             basic    credit card       M
3          104  los angeles               vip         paypal       F
4          105  los angeles               vip           Cash   Other

c. Standardizing Payment Methods

In [22]:
df['Payment_Method']=df['Payment_Method'].str.lower().replace({
    'credit card':'credit card',
    'paypal': 'paypal',
    'cash':'cash'
})
df

   Customer_ID         City Subscription_Type Payment_Method  Gender
0          101     new york             basic    credit card    Male
1          102     new york           premium         paypal  Female
2          103     new york             basic    credit card       M
3          104  los angeles               vip         paypal       F
4          105  los angeles               vip           cash   Other

d. Standardizing Gender Labels

In [24]:
df['Gender']=df['Gender'].str.lower().replace({
    'm':'male',
    'f':'female'
    
})
df

   Customer_ID         City Subscription_Type Payment_Method  Gender
0          101     new york             basic    credit card    male
1          102     new york           premium         paypal  female
2          103     new york             basic    credit card    male
3          104  los angeles               vip         paypal  female
4          105  los angeles               vip           cash   other

# 2. Encoding Categorical Data

 a) label encoding for ordinal data

In [28]:
mapping_subscription_type={'basic':1, 'premium':2, 'vip':3}
df['Subscription_Type']=df['Subscription_Type'].map(mapping_subscription_type)
df[['Subscription_Type']]

   Subscription_Type
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN

b) one hot encoding

In [38]:
df=pd.get_dummies(df,columns=['City','Payment_Method'])
df

KeyError: "None of [Index(['City', 'Payment_Method'], dtype='object')] are in the [columns]"

In [35]:
df = pd.get_dummies(df, columns=['City', 'Payment_Method'], drop_first=True)
print("\nOne-Hot Encoded Dataset:\n", df)

KeyError: "None of [Index(['City', 'Payment_Method'], dtype='object')] are in the [columns]"