# 7. Fixing Structural Errors

In [33]:
import pandas as pd
import numpy as np

data = {
    'Full_Name': ['Alice Smith', 'Bob_Jones', 'Charlie-Brown', 'David  White', 'Eve_King'],  # Different name formats
    'Date_of_Joining': ['2022/05/10', '10-05-2022', '2022.05.10', 'May 10, 2022', '2022-05-10'],  # Different date formats
    'Salary(USD)': ['$50,000', '60000$', '70000', '80,000', '90000'],  # Inconsistent salary formats
    'Department_Location': ['HR - NY', 'IT - SF', 'Finance - LA', 'HR-NY', 'IT, SF']  # Misaligned department-location info
}

df = pd.DataFrame(data)

df

       Full_Name Date_of_Joining Salary(USD) Department_Location
0    Alice Smith      2022/05/10     $50,000             HR - NY
1      Bob_Jones      10-05-2022      60000$             IT - SF
2  Charlie-Brown      2022.05.10       70000        Finance - LA
3   David  White    May 10, 2022      80,000               HR-NY
4       Eve_King      2022-05-10       90000              IT, SF

# 1. Splitting and Merging Columns

a) Splitting Department and Location

In [34]:
df[['Department','Location']]=df['Department_Location'].str.split('-',expand=True)
df.drop(columns=['Department_Location'],inplace=True)
df

       Full_Name Date_of_Joining Salary(USD) Department Location
0    Alice Smith      2022/05/10     $50,000        HR        NY
1      Bob_Jones      10-05-2022      60000$        IT        SF
2  Charlie-Brown      2022.05.10       70000   Finance        LA
3   David  White    May 10, 2022      80,000         HR       NY
4       Eve_King      2022-05-10       90000     IT, SF     None

b. Splitting Full Name into First and Last Name

In [ ]:
# df[['Name','Last Name']]=df['Full_Name'].str.replace('-','').str.replace('_','').str.split(' ',n=1,expand=True)
df.drop(columns=['Full_Name'],inplace=True)
df

# 2. Parsing Incorrect Data Entries

a. Converting Salary to Numeric Format

In [37]:
df['Salary(USD)'].unique()

array(['$50,000', '60000$', '70000', '80,000', '90000'], dtype=object)

In [42]:
df['Salary(USD)']=df['Salary(USD)'].replace({'\$':'',',':''},regex=True).astype(float)
df

  Date_of_Joining  Salary(USD) Department Location          Name Last Name
0      2022/05/10      50000.0        HR        NY         Alice     Smith
1      10-05-2022      60000.0        IT        SF      BobJones      None
2      2022.05.10      70000.0   Finance        LA  CharlieBrown      None
3    May 10, 2022      80000.0         HR       NY         David     White
4      2022-05-10      90000.0     IT, SF     None       EveKing      None